# Generated by Django 4.2.4 on 2023-08-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('present_images', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Markpresence',
        ),
    ]
