# Generated by Django 4.2.4 on 2023-08-08 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_delete_cameraimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
