# Generated by Django 4.2.4 on 2023-08-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='Null', upload_to='db_facerecog/training_video/'),
            preserve_default=False,
        ),
    ]
