# Generated by Django 4.2.4 on 2023-08-09 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_capturedimage_attendance_and_more'),
    ]

    operations = [
    ]
