# Generated by Django 4.2.4 on 2023-08-09 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20230808_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedimage',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.student'),
            preserve_default=False,
        ),
    ]
