# Generated by Django 4.2.4 on 2023-08-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_capturedimage_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.CharField(max_length=8),
        ),
    ]
